apiVersion: v1
kind: Service
metadata:
  name: {{ include "guitar-detect.fullname" . }}-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "guitar-detect.componentLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "guitar-detect.componentSelectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
